# .bashrc

PS1='[\[\033[0;31m\]\u\[\033[0m\]@\[\033[0;32m\]\h\[\033[0m\]:\[\033[1;34m\]\w\[\033[0m\]] $ '
export PS2='\[\033[0;31m\](>\[\033[0m\]'

alias ls='ls --color -N'
alias f='feh *'
alias lg='ls | grep -ai'

export LANGUAGE=en_US
export EDITOR=nvim
alias vi=nvim

